name: test-pipeline.yml

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up secret.yml
        env:
          APPLICATION_SECRET_CONTENT: ${{ secrets.APPLICATION_SECRET }}
        run: |
          cd ./src/main/resources
          touch ./application-secret.yml
          echo "$APPLICATION_SECRET_CONTENT" > ./application-secret.yml
          ls -a .

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: PR and PUSH Test Verification
        run: ./gradlew test